
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  . ~/.config/exercism/exercism_completion.zsh
fi

# Customize to your needs...
export CLICOLOR=1
TERM=xterm-256color

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
fpath=(/usr/local/share/zsh-completions $fpath)

alias "vim"="nvim"
alias "p"="python"
alias "ls"="exa"
alias "la"="ls -a"

bindkey '`' autosuggest-accept
export FZF_DEFAULT_OPTS='--height 40% --border'



#initialize Z (https://github.com/rupa/z) 
. "/usr/local/etc/profile.d/z.sh"
 

source ~/.fzf.zsh
alias config='/usr/bin/git --git-dir=/Users/ilyanoskov/.cfg/ --work-tree=/Users/ilyanoskov'
